public with sharing class Constants {
    public final static String PicklistMemberGenderMister = '先生';
    public final static String PicklistMemberGenderMiss = '小姐';

    public final static String PicklistCarTestRouteTypeUrban = '市區道路';
    public final static String PicklistCarTestRouteTypeMountain = '山區道路';
    public final static String PicklistCarTestRouteTypeHighway = '高速道路';
    public final static String PicklistCarTestRouteTypeOther = '其他';

    public final static String PicklistDealerAreaNorth = '北';
    public final static String PicklistDealerAreaSouth = '南';
    public final static String PicklistDealerAreaWest = '中';
    public final static String PicklistDealerAreaEast = '東';

    public final static String lineHost = 'linehost';
    public final static String lineCalloutTriggerPromotion = '/line/promotion';
    public final static String lineCalloutTriggerCarTestRoute = '/line/carTestRoute';
    public final static String lineCalloutTriggerDealer = '/line/dealer';

    public final static String smtHost = 'smthost';
}
