public with sharing class Constants {
    public final static String PicklistMemberGenderMister = '先生';
    public final static String PicklistMemberGenderMiss = '小姐';

    public final static String PicklistCarTestRouteTypeUrban = '市區道路';
    public final static String PicklistCarTestRouteTypeMountain = '山區道路';
    public final static String PicklistCarTestRouteTypeHighway = '高速道路';
    public final static String PicklistCarTestRouteTypeOther = '其他';

    public final static String PicklistDealerAreaNorth = '北';
    public final static String PicklistDealerAreaSouth = '南';
    public final static String PicklistDealerAreaMiddle = '中';
    public final static String PicklistDealerAreaEast = '東';

    public final static String PicklistPromotionPowerTypeGas = 'Drive-e 汽油車款';
    public final static String PicklistPromotionPowerTypeHybrid = '高效輕油電車款';
    public final static String PicklistPromotionPowerTypeHybridPhev = '雙能電動車款';

    public final static String PicklistPromotionStatusEnabled = '啟用';
    public final static String PicklistPromotionStatusDisabled = '停用';
    
    public final static String lineHost = 'linehost';
    public final static String lineCalloutTriggerPromotion = '/line/promotion';
    public final static String lineCalloutTriggerCarTestRoute = '/line/carTestRoute';
    public final static String lineCalloutTriggerDealer = '/line/dealer';

    public final static String lineCalloutHost = 'https://cloudservice.azure-api.net/volvo/api/test/';

    public final static String smtHost = 'smthost';
}
